---
apache_default_site:
  data: |
    ServerName {{ ansible_host }}
    ServerAdmin {{ apache_serveradmin }}

    DocumentRoot /srv/sites/master
    <Directory  "/srv/sites/master">
        Options FollowSymLinks
        AllowOverride None
        Require all granted
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined

    IncludeOptional sites-enabled/conf.d/*.conf

    <IfModule mod_ssl.c>
        <VirtualHost *:80>
            Redirect / https://{{ ansible_host }}/
        </VirtualHost>

        <VirtualHost _default_:443>
            SSLEngine On

            SSLCertificateFile  /etc/ssl/private/{{ apache_ssl.cert.file }}
            SSLCertificateKeyFile /etc/ssl/private/{{ apache_ssl.key.file }}
            {% if apache_ssl.chain is defined %}SSLCertificateChainFile /etc/ssl/private/{{ apache_ssl.chain.file }}{% endif %}

            <FilesMatch "\.(cgi|shtml|phtml|php)$">
                SSLOptions +StdEnvVars
            </FilesMatch>
            <Directory /usr/lib/cgi-bin>
                SSLOptions +StdEnvVars
            </Directory>

        </VirtualHost>
    </IfModule>
...
