---
asm_version: "41u"
asm_archive:
  name: "asm3-{{ asm_version }}"
  ext: ".tar.gz"
  path: "archives/asm3-{{ asm_version }}.tar.gz"

asm_path: "/srv/sites/asm"
asm_data: "/srv/data/asm"

asm_base_uri: /
asm_base_url: https://{{ ansible_host }}{{ asm_base_uri }}

asm_db:
  type: "MYSQL"
  port: 3306
  host: "localhost"
  name: "asm"
  user: "asm"
  pass: "{{ vault_asm_db.password }}"

asm_sitedefs:
    # Where to store media files.
    # database - media files are base64 encoded in the dbfs.content db column
    # file - media files are stored in a folder
    # s3 - media files are stored in amazon s3
    dbfs_store: "file"
...
