---
- hosts: "asm"
  become: "yes"
  roles:
    - "City-of-Bloomington.apache"
  vars:
    archive_name: "asm3-{{ asm_version }}"
    archive_path: "archives/asm3-{{ asm_version }}.tar.gz"
  tasks:
    - name: "Mysql setup"
      include_tasks: "tasks/mysql.yml"
      when: "asm_db.type == 'MYSQL'"

    - name: "Postgres setup"
      include_tasks: "tasks/postgresql.yml"
      when: "asm_db.type == 'POSTGRESQL'"

    - name: "Install Animal Shelter Manger dependencies"
      apt:
        name: "{{ packages }}"
        state: "present"
      vars:
        packages:
          - "libapache2-mod-wsgi-py3"
          - "make"
          - "imagemagick"
          - "wkhtmltopdf"
          - "memcached"
          - "curl"
          - "python3-lxml"
          - "python3-memcache"
          - "python3-pil"
          - "python3-requests"
          - "python3-webpy"

    - name: "Activate Apache WSGI Module"
      apache2_module:
        name: "wsgi"

    - name: "Create ASM directories"
      ansible.builtin.file:
        path: "{{ item }}"
        state: "directory"
        owner: "www-data"
        group: "staff"
        mode: "u=rwx,g=rwxs,o=rx"
      with_items:
        - "{{ asm_data }}"
        - "{{ asm_data }}/cache"
        - "{{ asm_data }}/media"
        - "{{ asm_data }}/wsgi"
        - "/srv/backups/asm"
        - "/var/log/cron"

    - name: "Extract release"
      ansible.builtin.unarchive:
        src:  "{{ archive_path }}"
        dest: "{{ asm_path | dirname }}"
        owner: 'www-data'
        group: 'staff'

    - name: "Symlink Release"
      ansible.builtin.file:
        path:  "{{ asm_path }}"
        src:   "{{ asm_path | dirname }}/{{ archive_name }}"
        state: 'link'
        owner: 'www-data'
        group: 'staff'

    - name: "Create Version File"
      ansible.builtin.template:
        src: "__version__.py"
        dest: "{{ asm_path }}/src/asm3/__version__.py"

    - name: "Update apache configuration"
      template:
        src: "{{ lookup('first_found', paths ) }}"
        dest: "/etc/apache2/sites-enabled/conf.d/asm.conf"
      vars:
        paths:
          - "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/templates/asm/apache.conf"
          - "{{ inventory_dir }}/group_vars/asm/templates/apache.conf"
          - "{{  playbook_dir }}/templates/apache.conf"
      notify: "apache_restart"

    - name: "Update sitedefs"
      template:
        src: "{{ lookup('first_found', paths ) }}"
        dest: "{{ asm_data }}/asm3.conf"
      vars:
        paths:
          - "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/templates/asm/asm3.conf"
          - "{{ inventory_dir }}/group_vars/asm/templates/asm3.conf"
          - "{{  playbook_dir }}/templates/asm3.conf"

    - name: "Install WSGI script"
      template:
        src: "{{ lookup('first_found', paths ) }}"
        dest: "{{ asm_data }}/wsgi/asm3.wsgi"
      vars:
        paths:
          - "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/templates/asm/asm3.wsgi"
          - "{{ inventory_dir }}/group_vars/asm/templates/asm3.wsgi"
          - "{{  playbook_dir }}/templates/asm3.wsgi"

    - name: "Install CRON"
      template:
        src: "{{ lookup('first_found', paths ) }}"
        dest: "/etc/cron.daily/asm"
        mode: "0755"
      vars:
        paths:
          - "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/templates/asm/cron.sh"
          - "{{ inventory_dir }}/group_vars/asm/templates/cron.sh"
          - "{{  playbook_dir }}/templates/cron.sh"
...
