---
- hosts: asm
  become: yes
  roles:
    - City-of-Bloomington.mysql
    - City-of-Bloomington.apache
  tasks:
    - name: Install Animal Shelter Manger dependencies
      apt:
        name: "{{ item }}"
        state: present
      tags: asm
      with_items:
        - libapache2-mod-wsgi
        - make
        - python
        - python-imaging
        - python-webpy
        - python-mysqldb
        - python-psycopg2
        - imagemagick
        - wkhtmltopdf
        - python-requests
        - python-ndg-httpsclient
        - python-pyasn1
        - memcached
        - python-memcache

    - name: "Activate Apache WSGI Module"
      apache2_module:
        name: "wsgi"

    - name: Create mysql database
      mysql_db:
        config_file: "{{ mysql_defaults_extra_file }}"
        name: "{{ asm_db.name }}"
        state: present
      no_log: True

    - name: "Create mysql user"
      mysql_user:
        name:     "{{ asm_db.user }}"
        password: "{{ asm_db.pass }}"
        priv:     "{{ asm_db.name }}.*:ALL"
        state: present
        config_file: "{{ mysql_defaults_extra_file }}"
      no_log: True

    - name: "Extract release"
      unarchive:
        src: "{{ asm_archive.path }}"
        dest: "/usr/local/src"
      register: release

    - name: "Remove old release"
      file:
        path: "{{ asm_path }}"
        state: "absent"
      when: release.changed

    - name: "Create ASM directories"
      file:
        path: "{{ item }}"
        state: "directory"
        owner: "www-data"
        group: "staff"
        mode: u=rwx,g=rwxs,o=rx
      with_items:
        - "{{ asm_path }}"
        - "{{ asm_data }}"
        - "{{ asm_data }}/cache"
        - "{{ asm_data }}/media"

    - name: "Install release"
      command: "rsync -rlv /usr/local/src/{{ asm_archive.name }}/ {{ asm_path }}/"
      when: release.changed

    - name: "Update apache configuration"
      template:
        src: "asm.conf"
        dest: "/etc/apache2/sites-enabled/conf.d/asm.conf"
      notify: "apache_restart"

    - name: "Update sitedefs"
      template:
        src: "sitedefs.py"
        dest: "{{ asm_path }}/src/sitedefs.py"

    - name: "Install CRON"
      template:
        src: "cron.sh"
        dest: "/etc/cron.daily/asm"
        mode: "0755"
...
